### ISSUE TITLE
App idea

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/mealplanner.net#1]
# Idea

Since my original Meal Planner is a basic but also very good project to learn about database connections and entity models in a language, I decided to rewrite this app using .NET 7 and C#.

# TODOs

- [x] ~~Create the database and tables in SQLite and/or SQL Server~~ (SQLite 3 automatically creates the database when first connecting to the db)
- [x] Create the entity models as `classlib`
- [x] Create the DatabaseContext and DatabaseContextExtensions as `classlib`
- [x] Add an `xunit` project for unit testing and check if the db connection can be established
- [x] Create a `console` app and rewrite the core functionality to it
